### ISSUE TITLE
deps.edn classifier syntax change

### ISSUE THREAD

**Issue by puredanger** [oconn/reagent-form#1]
Hi, I wanted to let you know that the syntax for classifiers in deps.edn files has changed with the latest release of clj (1.10.0.408). The classifier attribute is no longer used and instead the classifier is added to the lib name itself as groupId/artifactId$classifier.

In your deps.edn, you might want to switch to the next syntax like:

`org.clojure/clojurescript$aot {:mvn/version "1.10.64"}`

If you have any issues, feel free to file a ticket at https://dev.clojure.org/jira/browse/TDEPS for tools.deps.alpha.

**Comment by oconn** [comment]
Thanks for the heads up
